# Generated by Django 5.2.7 on 2026-07-04 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("makerpass", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JornadaDiaria",
        ),
    ]
